name: build
run-name: Build requested from ${{ github.actor }}.
on: workflow_dispatch
jobs:
  compile-typescript-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - run: npm i -g tsup
      - run: npm run build
